extends Node2D

onready var level = "res://Scenes/Node2D.tscn"
onready var loading = ("res://Scenes/Loading.tscn")

func _ready():
	print("Loading assets")
	load("res://Assets/UI/panel_background.png")
	load("res://Assets/cow/diving_mask.png")
	load("res://Assets/cow/idle/cow.png")
	load("res://Assets/cow/idle/cow1.png")
	load("res://Assets/cow/idle/cow2.png")
	load("res://Assets/cow/idle/cow3.png")
	load("res://Assets/cow/idle/cow4.png")
	load("res://Assets/cow/idle/cow5.png")
	load("res://Assets/cow/idle/cow6.png")
	load("res://Assets/cow/idle/cow7.png")
	load("res://Assets/cow/idle_underwater/cow.png")
	load("res://Assets/cow/idle_underwater/cow2.png")
	load("res://Assets/cow/idle_underwater/cow3.png")
	load("res://Assets/cow/idle_underwater/cow4.png")
	load("res://Assets/cow/idle_underwater/cow5.png")
	load("res://Assets/cow/idle_underwater/cow6.png")
	load("res://Assets/cow/idle_underwater/cow7.png")
	load("res://Assets/cow/idle_underwater/cow1.png")
	load("res://Assets/cow/running/cow1.png")
	load("res://Assets/cow/running/cow2.png")
	load("res://Assets/cow/running/cow3.png")
	load("res://Assets/cow/running/cow4.png")
	load("res://Assets/cow/running/cow5.png")
	load("res://Assets/cow/running_underwater/cow1.png")
	load("res://Assets/cow/running_underwater/cow2.png")
	load("res://Assets/cow/running_underwater/cow3.png")
	load("res://Assets/cow/running_underwater/cow4.png")
	load("res://Assets/cow/running_underwater/cow5.png")
	load("res://Assets/grass/grass-back/grass-back.png")
	load("res://Assets/grass/grass-back/grass-back2.png")
	load("res://Assets/grass/grass-back/grass-back3.png")
	load("res://Assets/grass/grass-back/grass-back4.png")
	load("res://Assets/grass/grass-front/grass-front1.png")
	load("res://Assets/grass/grass-front/grass-front2.png")
	load("res://Assets/grass/grass-front/grass-front3.png")
	load("res://Assets/grass/grass-front/grass-front4.png")
	load("res://Assets/ground/ground-mid.png")
	load("res://Assets/ground/ground-small.png")
	load("res://Assets/ground/ground-top.png")
	load("res://Assets/items/Light.png")
	load("res://Assets/items/carrot.png")
	load("res://Assets/items/door-closed.png")
	load("res://Assets/items/door-opened.png")
	load("res://Assets/items/help_panel.png")
	load("res://Assets/items/key.png")
	load("res://Assets/trees/bush.png")
	load("res://Assets/trees/leaf.png")
	load("res://Assets/trees/crown1.png")
	load("res://Assets/trees/crown2.png")
	load("res://Assets/trees/tree1.png")
	load("res://Assets/trees/tree2.png")
	load("res://Assets/water/water.png")
	load("res://Assets/background/grass-back.png")
	load("res://Assets/background/grass.png")
	load("res://Assets/background/ground-mid-old.png")
	load("res://Assets/background/ground-mid.png")
	load("res://Assets/UI/loading.png")
	load("res://Assets/background/grass-down.png")
	load("res://Assets/background/ground-top.png")
	load("res://Assets/background/ground-bot.png")
	load("res://Assets/UI/cursor.png")
	load("res://Assets/items/apple.png")
	load("res://Assets/animals/frog.png")
	load("res://Assets/animals/frog2.png")
	load("res://Assets/animals/frog3.png")
	load("res://Assets/animals/frog4.png")
	load("res://Assets/animals/fly.png")
	load("res://Assets/animals/fly2.png")
	load("res://Assets/items/rock.png")
	print("Loading shaders")
	load("res://Shaders/background.shader")
	load("res://Shaders/medium-wind.shader")
	load("res://Shaders/medium2-wind.shader")
	load("res://Shaders/slow-slow-wind.shader")
	load("res://Shaders/slow-wind.shader")
	load("res://Shaders/wind.shader")
	print("Done")
	print()
	
	Input.set_mouse_mode(Input.MOUSE_MODE_HIDDEN)
#	Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
	$RichTextLabel3.rect_position.y = get_viewport().size.y / 10 * -1
	print($RichTextLabel3.rect_position)

func _process(delta):
	$cursor.position = get_global_mouse_position()
	$cursor.rotation_degrees += 0.5 * delta * 100
	$loading.rotation_degrees += 1.5 * delta * 100
	if $loading.rotation_degrees >= 500:
		get_tree().change_scene(level)
